background { monitor = ; color = rgb(121315) }
input-field { monitor = ; size = 280, 50; outline_thickness = 2; outer_color = rgb(f2c94c); inner_color = rgb(121315); font_color = rgb(e8e6df); placeholder_text = <i>Password…</i>; position = 0, -20; halign = center; valign = center }
label { monitor = ; text = cmd[update:1000] echo "$(date '+%H:%M')"; color = rgb(e8e6df); font_size = 54; position = 0, 100; halign = center; valign = center }
